### ISSUE TITLE
Error: Unable to locate element [After Login It's not working]

### ISSUE THREAD

**Issue by parth23** [anniedotexe/Instagram-Like-Comment-Bot#4]
Getting below error after login into insta
![image](https://user-images.githubusercontent.com/17453977/132323414-85aa0ae6-9a75-41fd-94b6-de5878263bf8.png)

**Comment by parth23** [comment]
@anniedotexe Please help to resolve this issue.

**Comment by anniedotexe** [comment]
Hey, thanks for letting me know about the issue. I currently have as full
time job, so it might take a while for me to be able to help your. But I
will try to get it fixed as soon as I can.

**Comment by anniedotexe** [comment]
Hello,

It looks like Instagram has had some website code changes, so I have updated the Xpaths accordingly on the `insta-bot.py` file. I have tested the bot and everything looks like it is working correctly now.

Please download (or copy the code from) the `insta-bot.py` file that I just pushed.

Also, please make sure you have the correct [ChromeDriver](https://chromedriver.chromium.org/downloads) file downloaded since Chrome is now on version 93.0.4577.63.

If you run into any more problems, please let me know.

Thank you,
anniedotexe

**Comment by anniedotexe** [comment]
Also please let me know if it is working with no problems for you, so I can close this issue, thanks.

**Comment by anniedotexe** [comment]
Its been almost a week. I'm going to assume its all working now and close the issue. If you run into more problems, please open a new issue for it. Thanks.
